version = 1
SPDX-PackageName = "Kleff Template"
SPDX-PackageSupplier = "Kleff Hosting"
SPDX-PackageDownloadLocation = "https://github.com/kleffio/template"

[[annotations]]
path = "**"
SPDX-FileCopyrightText = "2025 Kleff Hosting"
SPDX-License-Identifier = "LicenseRef-Kleff-Public-License-1.0"

[[annotations]]
path = "LICENSES/**"
precedence = "aggregate"
